### ISSUE TITLE
Android Studio Render Failed

### ISSUE THREAD

**Issue by catkic** [nickbutcher/plaid#187]
when I open activity_home.xml
### 
`java.lang.NullPointerException
	at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:889)
	at android.animation.ValueAnimator.startAnimation(ValueAnimator.java:1174)
	at android.animation.ValueAnimator.start(ValueAnimator.java:996)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1010)
	at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
	at android.animation.StateListAnimator.start(StateListAnimator.java:188)
	at android.animation.StateListAnimator.setState(StateListAnimator.java:181)
	at android.view.View.drawableStateChanged(View.java:17870)
	at android.widget.TextView.drawableStateChanged(TextView.java:4089)
	at android.view.View.refreshDrawableState(View.java:17922)
	at android.view.View.dispatchAttachedToWindow(View.java:15427)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4493)
	at android.view.ViewGroup.addView(ViewGroup.java:4295)
	at android.view.ViewGroup.addView(ViewGroup.java:4235)
	at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:711)
	at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
	at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7877)
	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7835)
	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7823)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1565)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
	at android.support.v7.widget.RecyclerView.onLayout_Original(RecyclerView.java:3844)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java)
	at android.view.View.layout(View.java:17523)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.support.v4.widget.DrawerLayout.onLayout_Original(DrawerLayout.java:1217)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java)
	at android.view.View.layout(View.java:17523)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17523)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:17523)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:345)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:368)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:567)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:549)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:549)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$1(RenderTask.java:680)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

![image](https://cloud.githubusercontent.com/assets/13983542/26108640/b89d1182-3a7f-11e7-863b-a6b3f42c9963.png)

and my sdk:

![image](https://cloud.githubusercontent.com/assets/13983542/26108689/d60f48ac-3a7f-11e7-94ab-e10314445769.png)

![image](https://cloud.githubusercontent.com/assets/13983542/26108696/deddd494-3a7f-11e7-9d65-f40a731402f6.png)

**Comment by BannerCoe** [comment]
I think that was 

1. Update SDK Build-Tools
2. Uncheck Gradle off-line work in android studio setting (or preference)
3. Clean and Rebuild the project.
