### ISSUE TITLE
OOM Crash

### ISSUE THREAD

**Issue by Laimiux** [nickbutcher/plaid#22]
It happens on two different genymotion devices with 5.0 and 5.1.0, after I browse few grid items.

```
11-02 11:46:49.654 2492-2492/io.plaidapp E/art: Throwing OutOfMemoryError "Failed to allocate a 1555212 byte allocation with 828657 free bytes and 809KB until OOM"
11-02 11:46:49.654 2492-2492/io.plaidapp D/AndroidRuntime: Shutting down VM
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime: FATAL EXCEPTION: main
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime: Process: io.plaidapp, PID: 2492
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 1555212 byte allocation with 828657 free bytes and 809KB until OOM
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.graphics.Bitmap.nativeCreate(Native Method)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.transition.TransitionUtils.createViewBitmap(TransitionUtils.java:165)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.app.SharedElementCallback.onCaptureSharedElementSnapshot(SharedElementCallback.java:177)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.app.ActivityTransitionCoordinator.captureSharedElementState(ActivityTransitionCoordinator.java:767)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.app.ActivityTransitionCoordinator.captureSharedElementState(ActivityTransitionCoordinator.java:690)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.app.EnterTransitionCoordinator.sendSharedElementDestination(EnterTransitionCoordinator.java:194)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.app.EnterTransitionCoordinator.viewsReady(EnterTransitionCoordinator.java:121)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.app.EnterTransitionCoordinator.triggerViewsReady(EnterTransitionCoordinator.java:139)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.app.EnterTransitionCoordinator.viewInstancesReady(EnterTransitionCoordinator.java:100)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.app.ActivityTransitionState.startEnter(ActivityTransitionState.java:206)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.app.ActivityTransitionState.enterReady(ActivityTransitionState.java:186)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.app.Activity.onNewActivityOptions(Activity.java:5503)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.app.ActivityThread.onNewActivityOptions(ActivityThread.java:2507)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
11-02 11:46:49.654 2492-2492/io.plaidapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by Bringoff** [comment]
The same problem on standard emulator. Looks like it's because of lots of big images.
