### ISSUE TITLE
Crash after logging into Dribble

### ISSUE THREAD

**Issue by alexjlockwood** [nickbutcher/plaid#259]
```
E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.plaidapp.data.api.dribbble.model.User.name' on a null object reference
E AndroidRuntime: 	at io.plaidapp.ui.DribbbleLogin$1.onResponse(DribbbleLogin.java:135)
E AndroidRuntime: 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by nickbutcher** [comment]
"fixed" in 5ac21d4
