### ISSUE TITLE
[MOD] Crash in release APK build

### ISSUE THREAD

**Issue by nickbutcher** [nickbutcher/plaid#344]
Performing a release build (of ba8b5e8) succeeds, but crashes when trying to launch new screens.

Clicking on a Dribbble shot:

```
2018-06-26 16:42:59.716 1618-1618/io.plaidapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.plaidapp, PID: 1618
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{io.plaidapp/io.plaidapp.ui.dribbble.DribbbleShot}: java.lang.ClassNotFoundException: Didn't find class "io.plaidapp.ui.dribbble.DribbbleShot" on path: DexPathList[[zip file "/data/app/io.plaidapp-Kew13qYXEW8JGTLm6TL6xg==/base.apk"],nativeLibraryDirectories=[/data/app/io.plaidapp-Kew13qYXEW8JGTLm6TL6xg==/lib/arm64, /data/app/io.plaidapp-Kew13qYXEW8JGTLm6TL6xg==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2843)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.plaidapp.ui.dribbble.DribbbleShot" on path: DexPathList[[zip file "/data/app/io.plaidapp-Kew13qYXEW8JGTLm6TL6xg==/base.apk"],nativeLibraryDirectories=[/data/app/io.plaidapp-Kew13qYXEW8JGTLm6TL6xg==/lib/arm64, /data/app/io.plaidapp-Kew13qYXEW8JGTLm6TL6xg==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

Clicking FAB on main screen:

```
2018-06-26 16:41:27.610 32485-32485/io.plaidapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.plaidapp, PID: 32485
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{io.plaidapp/io.plaidapp.ui.designernews.DesignerNewsLogin}: java.lang.ClassNotFoundException: Didn't find class "io.plaidapp.ui.designernews.DesignerNewsLogin" on path: DexPathList[[zip file "/data/app/io.plaidapp-Kew13qYXEW8JGTLm6TL6xg==/base.apk"],nativeLibraryDirectories=[/data/app/io.plaidapp-Kew13qYXEW8JGTLm6TL6xg==/lib/arm64, /data/app/io.plaidapp-Kew13qYXEW8JGTLm6TL6xg==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2843)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.plaidapp.ui.designernews.DesignerNewsLogin" on path: DexPathList[[zip file "/data/app/io.plaidapp-Kew13qYXEW8JGTLm6TL6xg==/base.apk"],nativeLibraryDirectories=[/data/app/io.plaidapp-Kew13qYXEW8JGTLm6TL6xg==/lib/arm64, /data/app/io.plaidapp-Kew13qYXEW8JGTLm6TL6xg==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by keyboardsurfer** [comment]
Assuming the apk gets installed via `adb install` directly rather than using either `bundletool` or `adb install-multiple` with all apks.

Using the `com.android.dynamic-feature` plugin creates an apk with code and resources for each dynamic feature. These are completely unbundled from the `app` apk.

To use [bundletool](https://github.com/google/bundletool/releases), you'll first need to download it.

Then, in order to install and run every module of a release build via CLI then execute:

```
./gradlew bundleRelease
cd app/build/outputs/bundle/release
# replace debug.keystore with release keystore
bundletool  build-apks --connected-device --bundle=plaid.aab \
--ks=~/.android/debug.keystore --ks-key-alias=androiddebugkey \
--ks-pass=pass:android --output=plaid.apks
bundletool install-apks --apks=plaid.apks
````

Or add the keystore info to AndroidStudio and install it from there, checking all dynamic-features to be installed alongside the app module.
