### ISSUE TITLE
Search result crashes

### ISSUE THREAD

**Issue by IgorGanapolsky** [nickbutcher/plaid#481]
When trying to perform a search and pressing on a result, I get this crash:
> 2018-08-21 12:12:58.411 21463-21463/io.plaidapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.plaidapp, PID: 21463
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.plaidapp/io.plaidapp.dribbble.ui.shot.ShotActivity}: java.lang.IllegalStateException: Could not retrieve shot 4635899
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Could not retrieve shot 4635899
        at io.plaidapp.dribbble.ui.shot.ShotViewModel.<init>(ShotViewModel.kt:50)
        at io.plaidapp.dribbble.ui.shot.ShotViewModelFactory.create(ShotViewModelFactory.kt:40)
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:134)
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:102)
        at io.plaidapp.dribbble.ui.shot.ShotActivity.onCreate(ShotActivity.kt:126)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)

**Comment by florina-muntenescu** [comment]
@IgorGanapolsky can you tell us more about what you did before? Thanks!

**Comment by IgorGanapolsky** [comment]
Please see screen recording:
https://drive.google.com/open?id=1kpBeRoVWb_P9JIORH_o5MhWLNS7_rkft

**Comment by florina-muntenescu** [comment]
Thank you @IgorGanapolsky !
