### ISSUE TITLE
Crash upon clicking item in home screen

### ISSUE THREAD

**Issue by guylis** [nickbutcher/plaid#504]
Crash when pressing item in home screen (project installed on windows using android studio 3.1.3)

    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{io.plaidapp/io.plaidapp.dribbble.ui.shot.ShotActivity}: java.lang.ClassNotFoundException: Didn't find class "io.plaidapp.dribbble.ui.shot.ShotActivity" on path: DexPathList[[zip file "/data/app/io.plaidapp-1vNkXuyIP6ddbZUmLTNiAw==/base.apk"],nativeLibraryDirectories=[/data/app/io.plaidapp-1vNkXuyIP6ddbZUmLTNiAw==/lib/arm64, /data/app/io.plaidapp-1vNkXuyIP6ddbZUmLTNiAw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.plaidapp.dribbble.ui.shot.ShotActivity" on path: DexPathList[[zip file "/data/app/io.plaidapp-1vNkXuyIP6ddbZUmLTNiAw==/base.apk"],nativeLibraryDirectories=[/data/app/io.plaidapp-1vNkXuyIP6ddbZUmLTNiAw==/lib/arm64, /data/app/io.plaidapp-1vNkXuyIP6ddbZUmLTNiAw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by ataulm** [comment]
Can you try again with AS 3.2? I'm pretty sure earlier is not supported.

**Comment by guylis** [comment]
Hi
This indeed fixed the problem
Thank you very much.
I did not see a mention of this since 3.2 is still a preview so I wasn't using it.
Was it mentioned? If not, maybe write it in the readme

**Comment by ataulm** [comment]
No, it's not mentioned - I have raised a PR to address this.

It's using dynamic features or app bundle or something that predicates the use of AS 3.2 - the app should be buildable via command line though.
