### ISSUE TITLE
NullPointerException in SearchDataManager

### ISSUE THREAD

**Issue by IgorGanapolsky** [nickbutcher/plaid#536]
Steps to reproduce:
1) launch the app
2) tap the search widget
3) tap the left arrow to close search widget
4) observe the following crash:

>  Process: io.plaidapp, PID: 10530
    java.lang.RuntimeException: Unable to destroy activity {io.plaidapp/io.plaidapp.ui.search.SearchActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.plaidapp.core.dribbble.data.ShotsRepository.cancelAllSearches()' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4458)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4476)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.plaidapp.core.dribbble.data.ShotsRepository.cancelAllSearches()' on a null object reference
        at io.plaidapp.core.data.SearchDataManager.cancelLoading(SearchDataManager.java:78)
        at io.plaidapp.ui.search.SearchActivity.onDestroy(SearchActivity.java:202)
        at android.app.Activity.performDestroy(Activity.java:7395)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1306)

**Comment by ataulm** [comment]
Fixed in https://github.com/nickbutcher/plaid/pull/534
