### ISSUE TITLE
Pressing search causes the application to crash

### ISSUE THREAD

**Issue by qmar** [nickbutcher/plaid#6]
Hey,

found a crash on LG G2, Android 5.0.1

Steps to reproduce:
1. Open app
2. Press search on action bar

`FATAL EXCEPTION: main
Process: io.plaidapp, PID: 24700
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.setState(int[])' on a null object reference
at android.widget.SearchView.updateFocusedState(SearchView.java:861)
at android.widget.SearchView.access$000(SearchView.java:95)
at android.widget.SearchView$2.run(SearchView.java:165)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5292)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703))`

**Comment by Simon-Raes** [comment]
Same on an LG G3 with 5.0.1.

**Comment by thegumza** [comment]
same on HTC Desire EYE 5.0.2

**Comment by jbaginski** [comment]
reproduced with moto g (2nd gen) v5.0.2
