### ISSUE TITLE
I got this bug

### ISSUE THREAD

**Issue by NewXuSoft** [nickbutcher/plaid#69]
Process: io.plaidapp, PID: 8269
                                                           java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling
                                                               at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2161)
                                                               at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:4275)
                                                               at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:9948)
                                                               at android.support.v7.widget.RecyclerView$Adapter.notifyItemInserted(RecyclerView.java:5850)
                                                               at io.plaidapp.ui.FeedAdapter.dataStartedLoading(FeedAdapter.java:633)
                                                               at io.plaidapp.data.BaseDataManager.dispatchLoadingStartedCallbacks(BaseDataManager.java:166)
                                                               at io.plaidapp.data.BaseDataManager.loadStarted(BaseDataManager.java:73)
                                                               at io.plaidapp.data.DataManager.loadSource(DataManager.java:78)
                                                               at io.plaidapp.data.DataManager.loadAllDataSources(DataManager.java:59)
                                                               at io.plaidapp.ui.HomeActivity$4.onLoadMore(HomeActivity.java:183)
                                                               at io.plaidapp.ui.recyclerview.InfiniteScrollListener.onScrolled(InfiniteScrollListener.java:54)
                                                               at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:3948)
                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3102)
                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2914)
                                                               at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1430)
                                                               at android.support.v7.widget.RecyclerView.access$400(RecyclerView.java:147)
                                                               at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:285)
                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:586)
                                                               at android.view.Choreographer.doFrame(Choreographer.java:555)
                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:135)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5313)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1116)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)

**Comment by nickbutcher** [comment]
Looks like an issue with RecyclerView in 23.2.0. Tracking here:
https://code.google.com/p/android/issues/detail?id=202046
