### ISSUE TITLE
android.view.InflateException

### ISSUE THREAD

**Issue by lawloretienne** [nickbutcher/plaid#70]
After i downgraded supportLibVersion = '23.1.1' to prevent the recyclerview issue from coming up and crashing the app, I ran the app and then clicked on one of the items in the recyclerview which triggered the crash below

03-01 16:35:58.179 14818-14818/io.plaidapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: io.plaidapp, PID: 14818
                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{io.plaidapp/io.plaidapp.ui.DribbbleShot}: android.view.InflateException: Binary XML file line #48: Binary XML file line #48: Error inflating class android.widget.Button
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                              Caused by: android.view.InflateException: Binary XML file line #48: Binary XML file line #48: Error inflating class android.widget.Button
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                 at io.plaidapp.ui.DribbbleShot.onCreate(DribbbleShot.java:169)
                                                                 at android.app.Activity.performCreate(Activity.java:6251)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                              Caused by: android.view.InflateException: Binary XML file line #48: Error inflating class android.widget.Button
                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                 at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                                 at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                 at io.plaidapp.ui.DribbbleShot.onCreate(DribbbleShot.java:169) 
                                                                 at android.app.Activity.performCreate(Activity.java:6251) 
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                              Caused by: java.lang.reflect.InvocationTargetException
                                                                 at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                 at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                                                                 at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694) 
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762) 
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                 at io.plaidapp.ui.DribbbleShot.onCreate(DribbbleShot.java:169) 
                                                                 at android.app.Activity.performCreate(Activity.java:6251) 
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                              Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 24: TypedValue{t=0x3/d=0x3f5 "res/color/secondary_text_material_dark.xml" a=1 r=0x1060119}
                                                                 at android.content.res.TypedArray.getColor(TypedArray.java:447)
                                                                 at android.widget.TextView.<init>(TextView.java:738)
                                                                 at android.widget.Button.<init>(Button.java:109)
                                                                 at android.widget.Button.<init>(Button.java:105)
                                                                 at android.widget.Button.<init>(Button.java:101)
                                                                 at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                 at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                                                                 at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694) 
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762) 
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                 at io.plaidapp.ui.DribbbleShot.onCreate(DribbbleShot.java:169) 
                                                                 at android.app.Activity.performCreate(Activity.java:6251) 
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by nickbutcher** [comment]
Hmmm, that screen doesn't use a RecyclerView, it's a ListView so the Support Lib downgrade sounds like a red herring.  Looks like you're having trouble finding a resource id, could you try cleaning and rebuilding to refresh the resources table? Are you using instant run?  Might also complicate things.

**Comment by lawloretienne** [comment]
Thanks @nickbutcher . Cleaning and rebuilding the project worked.  Now it doesn't crash after i click on one of the items in the adapter.  Btw, I love this project.  Great job on this.

**Comment by nickbutcher** [comment]
@lawloretienne glad that sorted it & thanks!
