### ISSUE TITLE
NullPointerException when i clicked number of followers

### ISSUE THREAD

**Issue by markic22** [nickbutcher/plaid#89]
Just wanted to inform you about one little bug in your application.  
`java.lang.RuntimeException: Unable to start activity ComponentInfo{io.plaidapp/io.plaidapp.ui.PlayerSheet}: java.lang.NullPointerException: Attempt to read from field 'int io.plaidapp.data.api.dribbble.model.User.followers_count' on a null object reference
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                               at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:158)
                                                               at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                            Caused by: java.lang.NullPointerException: Attempt to read from field 'int io.plaidapp.data.api.dribbble.model.User.followers_count' on a null object reference
                                                               at io.plaidapp.ui.PlayerSheet.onCreate(PlayerSheet.java:142)`

**Comment by nickbutcher** [comment]
Thanks for reporting. Can you provide any more details on the steps to reach this state? I'm trying to figure out when the mode is in the intent extras but not the Player object? Also not sure what to do in this state!! Thanks.

**Comment by markic22** [comment]
I just click on one random article, then I click on user icon and then on followers and that happens. Problem is that the player is already null in PlayerActivity, from which you trigger PlayerSheet. In DriblerShot you check if user has shots_cuont more than 0
`   
                    if (shot.user.shots_count > 0) { // legit user object
                        player.putExtra(PlayerActivity.EXTRA_PLAYER, shot.user);
                    } else {
                       .......
                    ActivityOptions options =
                            ActivityOptions.makeSceneTransitionAnimation(DribbbleShot.this,
                                    playerAvatar, getString(R.string.transition_player_avatar));
                    startActivity(player, options.toBundle());
                }
            };`

And in all cases that i tried all had 0 shots_counts so it crashes on every user for me.
